var dict = {
  __Type: "WeatherPresetData",
  tCloudLayers: [
    {
      __Type: "CloudLayerData",
      dvDensityMultiplier: {
        __Type: "RangeDataValue",
        ID: 0,
        icon: "",
        name: "TT:MENU.WEATHER_TOOLBAR_PANEL_CLOUD_LAYER_SETTINGS_DENSITY",
        valueStr: "",
        value: 1,
        type: "",
        unit: "",
        quality: 0,
        html: "",
        userTag: 0,
        min: 0,
        max: 5,
        step: 0.009999999776482582,
        clamp_min: 0,
        clamp_max: 5,
        percent: 0,
      },
      dvCoverageRatio: {
        __Type: "RangeDataValue",
        ID: 0,
        icon: "",
        name: "Coverage : Clear",
        valueStr: "",
        value: 0,
        type: "",
        unit: "%",
        quality: 0,
        html: "",
        userTag: 0,
        min: 0,
        max: 100,
        step: 1,
        clamp_min: 0,
        clamp_max: 100,
        percent: 0,
      },
      dvCloudScatteringRatio: {
        __Type: "RangeDataValue",
        ID: 0,
        icon: "",
        name: "TT:MENU.WEATHER_TOOLBAR_PANEL_CLOUD_LAYER_SETTINGS_SCATTER",
        valueStr: "",
        value: 0,
        type: "",
        unit: "%",
        quality: 0,
        html: "",
        userTag: 0,
        min: 0,
        max: 100,
        step: 1,
        clamp_min: 0,
        clamp_max: 100,
        percent: 0,
      },
      dvAltitudeBot: {
        __Type: "RangeDataValue",
        ID: 0,
        icon: "",
        name: "TT:MENU.WEATHER_TOOLBAR_PANEL_CLOUD_LAYER_SETTINGS_ALT_BOT",
        valueStr: "",
        value: 8202.099737532808,
        type: "",
        unit: "Ft",
        quality: 0,
        html: "",
        userTag: 0,
        min: -1640,
        max: 60000,
        step: 10,
        clamp_min: -1640,
        clamp_max: 8202.099609375,
        percent: 0,
      },
      dvAltitudeTop: {
        __Type: "RangeDataValue",
        ID: 0,
        icon: "",
        name: "TT:MENU.WEATHER_TOOLBAR_PANEL_CLOUD_LAYER_SETTINGS_ALT_TOP",
        valueStr: "",
        value: 8202.099737532808,
        type: "",
        unit: "Ft",
        quality: 0,
        html: "",
        userTag: 0,
        min: -1640,
        max: 60000,
        step: 10,
        clamp_min: 8202.099609375,
        clamp_max: 60000,
        percent: 0,
      },
    },
    {
      __Type: "CloudLayerData",
      dvDensityMultiplier: {
        __Type: "RangeDataValue",
        ID: 0,
        icon: "",
        name: "TT:MENU.WEATHER_TOOLBAR_PANEL_CLOUD_LAYER_SETTINGS_DENSITY",
        valueStr: "",
        value: 1,
        type: "",
        unit: "",
        quality: 0,
        html: "",
        userTag: 0,
        min: 0,
        max: 5,
        step: 0.009999999776482582,
        clamp_min: 0,
        clamp_max: 5,
        percent: 0,
      },
      dvCoverageRatio: {
        __Type: "RangeDataValue",
        ID: 0,
        icon: "",
        name: "Coverage : Clear",
        valueStr: "",
        value: 0,
        type: "",
        unit: "%",
        quality: 0,
        html: "",
        userTag: 0,
        min: 0,
        max: 100,
        step: 1,
        clamp_min: 0,
        clamp_max: 100,
        percent: 0,
      },
      dvCloudScatteringRatio: {
        __Type: "RangeDataValue",
        ID: 0,
        icon: "",
        name: "TT:MENU.WEATHER_TOOLBAR_PANEL_CLOUD_LAYER_SETTINGS_SCATTER",
        valueStr: "",
        value: 0,
        type: "",
        unit: "%",
        quality: 0,
        html: "",
        userTag: 0,
        min: 0,
        max: 100,
        step: 1,
        clamp_min: 0,
        clamp_max: 100,
        percent: 0,
      },
      dvAltitudeBot: {
        __Type: "RangeDataValue",
        ID: 0,
        icon: "",
        name: "TT:MENU.WEATHER_TOOLBAR_PANEL_CLOUD_LAYER_SETTINGS_ALT_BOT",
        valueStr: "",
        value: 22965.879265091862,
        type: "",
        unit: "Ft",
        quality: 0,
        html: "",
        userTag: 0,
        min: -1640,
        max: 60000,
        step: 10,
        clamp_min: -1640,
        clamp_max: 22965.87890625,
        percent: 0,
      },
      dvAltitudeTop: {
        __Type: "RangeDataValue",
        ID: 0,
        icon: "",
        name: "TT:MENU.WEATHER_TOOLBAR_PANEL_CLOUD_LAYER_SETTINGS_ALT_TOP",
        valueStr: "",
        value: 22965.879265091862,
        type: "",
        unit: "Ft",
        quality: 0,
        html: "",
        userTag: 0,
        min: -1640,
        max: 60000,
        step: 10,
        clamp_min: 22965.87890625,
        clamp_max: 60000,
        percent: 0,
      },
    },
    {
      __Type: "CloudLayerData",
      dvDensityMultiplier: {
        __Type: "RangeDataValue",
        ID: 0,
        icon: "",
        name: "TT:MENU.WEATHER_TOOLBAR_PANEL_CLOUD_LAYER_SETTINGS_DENSITY",
        valueStr: "",
        value: 1,
        type: "",
        unit: "",
        quality: 0,
        html: "",
        userTag: 0,
        min: 0,
        max: 5,
        step: 0.009999999776482582,
        clamp_min: 0,
        clamp_max: 5,
        percent: 0,
      },
      dvCoverageRatio: {
        __Type: "RangeDataValue",
        ID: 0,
        icon: "",
        name: "Coverage : Overcast",
        valueStr: "",
        value: 91,
        type: "",
        unit: "%",
        quality: 0,
        html: "",
        userTag: 0,
        min: 0,
        max: 100,
        step: 1,
        clamp_min: 0,
        clamp_max: 100,
        percent: 0,
      },
      dvCloudScatteringRatio: {
        __Type: "RangeDataValue",
        ID: 0,
        icon: "",
        name: "TT:MENU.WEATHER_TOOLBAR_PANEL_CLOUD_LAYER_SETTINGS_SCATTER",
        valueStr: "",
        value: 50,
        type: "",
        unit: "%",
        quality: 0,
        html: "",
        userTag: 0,
        min: 0,
        max: 100,
        step: 1,
        clamp_min: 0,
        clamp_max: 100,
        percent: 0,
      },
      dvAltitudeBot: {
        __Type: "RangeDataValue",
        ID: 0,
        icon: "",
        name: "TT:MENU.WEATHER_TOOLBAR_PANEL_CLOUD_LAYER_SETTINGS_ALT_BOT",
        valueStr: "",
        value: 32808.39895013123,
        type: "",
        unit: "Ft",
        quality: 0,
        html: "",
        userTag: 0,
        min: -1640,
        max: 60000,
        step: 10,
        clamp_min: -1640,
        clamp_max: 33628.609375,
        percent: 0,
      },
      dvAltitudeTop: {
        __Type: "RangeDataValue",
        ID: 0,
        icon: "",
        name: "TT:MENU.WEATHER_TOOLBAR_PANEL_CLOUD_LAYER_SETTINGS_ALT_TOP",
        valueStr: "",
        value: 33628.60892388451,
        type: "",
        unit: "Ft",
        quality: 0,
        html: "",
        userTag: 0,
        min: -1640,
        max: 60000,
        step: 10,
        clamp_min: 32808.3984375,
        clamp_max: 60000,
        percent: 0,
      },
    },
  ],
  tWindLayers: [
    {
      __Type: "WindLayerData",
      gustWaveData: {
        __Type: "GustWaveData",
        dvAngleRad: {
          __Type: "RangeDataValue",
          ID: 0,
          icon: "",
          name: "TT:MENU.WEATHER_WIND_FROM",
          valueStr: "",
          value: 4.71238899230957,
          type: "",
          unit: "°",
          quality: 0,
          html: "",
          userTag: 0,
          min: 0,
          max: 6.2831854820251465,
          step: 0.01745329238474369,
          clamp_min: 0,
          clamp_max: 6.2831854820251465,
          percent: 0,
        },
        dvIntervalS: {
          __Type: "RangeDataValue",
          ID: 0,
          icon: "",
          name: "TT:MENU.WEATHER_TOOLBAR_PANEL_WIND_LAYER_SETTINGS_GUST_PER_MINUTE",
          valueStr: "",
          value: 35,
          type: "",
          unit: "",
          quality: 0,
          html: "",
          userTag: 0,
          min: 1,
          max: 18,
          step: 1,
          clamp_min: 1,
          clamp_max: 18,
          percent: 0,
        },
        dvSpeedMultiplier: {
          __Type: "RangeDataValue",
          ID: 0,
          icon: "",
          name: "TT:MENU.WEATHER_TOOLBAR_PANEL_WIND_LAYER_SETTINGS_SPEED",
          valueStr: "",
          value: 1,
          type: "",
          unit: "M/s",
          quality: 0,
          html: "",
          userTag: 0,
          min: 0,
          max: 2,
          step: 0.009999999776482582,
          clamp_min: 0,
          clamp_max: 2,
          percent: 0,
        },
      },
      dvAltitude: {
        __Type: "RangeDataValue",
        ID: 0,
        icon: "",
        name: "ALTITUDE",
        valueStr: "",
        value: 0,
        type: "",
        unit: "Ft",
        quality: 0,
        html: "",
        userTag: 0,
        min: -1640,
        max: 60000,
        step: 10,
        clamp_min: -1640,
        clamp_max: 60000,
        percent: 0,
      },
      dvAngleRad: {
        __Type: "RangeDataValue",
        ID: 0,
        icon: "",
        name: "TT:MENU.WEATHER_WIND_FROM",
        valueStr: "",
        value: 4.71238899230957,
        type: "",
        unit: "°",
        quality: 0,
        html: "",
        userTag: 0,
        min: 0,
        max: 6.2831854820251465,
        step: 0.01745329238474369,
        clamp_min: 0,
        clamp_max: 6.2831854820251465,
        percent: 0,
      },
      dvSpeed: {
        __Type: "RangeDataValue",
        ID: 0,
        icon: "",
        name: "TT:MENU.WEATHER_TOOLBAR_PANEL_WIND_LAYER_SETTINGS_SPEED",
        valueStr: "",
        value: 0.5144444704055786,
        type: "",
        unit: "M/s",
        quality: 0,
        html: "",
        userTag: 0,
        min: 0,
        max: 77.16999816894531,
        step: 1,
        clamp_min: 0,
        clamp_max: 77.16999816894531,
        percent: 0,
      },
    },
  ],
  index: 2,
  bIsRemovable: false,
  bIsValid: true,
  sPresetName: "TT:MENU.WEATHERTYPE_9CLEAR_SKY",
  oSettings: {
    __Type: "WeatherPresetSettingData",
    dvPrecipitation: {
      __Type: "RangeDataValue",
      ID: 0,
      icon: "",
      name: "TT:MENU.WEATHER_TOOLBAR_PANEL_SETTINGS_PRECIPITATIONS",
      valueStr: "",
      value: 0,
      type: "",
      unit: "mm/h",
      quality: 0,
      html: "",
      userTag: 0,
      min: 0,
      max: 30,
      step: 0.10000000149011612,
      clamp_min: 0,
      clamp_max: 30,
      percent: 0,
    },
    dvMSLPressure: {
      __Type: "RangeDataValue",
      ID: 0,
      icon: "",
      name: "Pressure MSL",
      valueStr: "",
      value: 1013.25,
      type: "",
      unit: "hPa",
      quality: 0,
      html: "",
      userTag: 0,
      min: 948,
      max: 1084,
      step: 0.25,
      clamp_min: 948,
      clamp_max: 1084,
      percent: 0,
    },
    dvMSLGLTemperature: {
      __Type: "RangeDataValue",
      ID: 0,
      icon: "",
      name: "Temperature MSL / ISA + 10",
      valueStr: "",
      value: 14.999993896484398,
      type: "",
      unit: "°C",
      quality: 0,
      html: "",
      userTag: 0,
      min: -90,
      max: 60,
      step: 0.5,
      clamp_min: -90,
      clamp_max: 60,
      percent: 0,
    },
    dvPollution: {
      __Type: "RangeDataValue",
      ID: 0,
      icon: "",
      name: "TT:MENU.WEATHER_TOOLBAR_PANEL_CLOUD_LAYER_SETTINGS_POLLUTION",
      valueStr: "",
      value: 0,
      type: "",
      unit: "%",
      quality: 0,
      html: "",
      userTag: 0,
      min: 0,
      max: 100,
      step: 1,
      clamp_min: 0,
      clamp_max: 100,
      percent: 0,
    },
    dvSnowCover: {
      __Type: "RangeDataValue",
      ID: 0,
      icon: "",
      name: "TT:MENU.WEATHER_TOOLBAR_PANEL_SETTINGS_GROUND_SNOW",
      valueStr: "",
      value: 0,
      type: "",
      unit: "cm",
      quality: 0,
      html: "",
      userTag: 0,
      min: 0,
      max: 75,
      step: 1,
      clamp_min: 0,
      clamp_max: 75,
      percent: 0,
    },
    dvHumidityMultiplier: {
      __Type: "RangeDataValue",
      ID: 0,
      icon: "",
      name: "TT:MENU.WEATHER_TOOLBAR_PANEL_SETTINGS_HUMIDITY",
      valueStr: "",
      value: 1,
      type: "",
      unit: "",
      quality: 0,
      html: "",
      userTag: 0,
      min: 1,
      max: 20,
      step: 0.10000000149011612,
      clamp_min: 1,
      clamp_max: 20,
      percent: 0,
    },
    dvThunderstormRatio: {
      __Type: "RangeDataValue",
      ID: 0,
      icon: "",
      name: "Lightning",
      valueStr: "",
      value: 0,
      type: "",
      unit: "%",
      quality: 0,
      html: "",
      userTag: 0,
      min: 0,
      max: 100,
      step: 1,
      clamp_min: 0,
      clamp_max: 100,
      percent: 0,
    },
    bIsAltitudeAMGL: true,
  },
  oConfig: {
    __Type: "WeatherPresetConfigData",
    dvMinAltitude: {
      __Type: "DataValue",
      ID: 0,
      icon: "",
      name: "MINIMAL_ALTITUDE",
      valueStr: "",
      value: -1640,
      type: "",
      unit: "Ft",
      quality: 0,
      html: "",
      userTag: 0,
    },
    dvMaxAltitude: {
      __Type: "DataValue",
      ID: 0,
      icon: "",
      name: "MAXIMAL_ALTITUDE",
      valueStr: "",
      value: 60000,
      type: "",
      unit: "Ft",
      quality: 0,
      html: "",
      userTag: 0,
    },
    daDvAltitudeLines: [
      {
        __Type: "DataValue",
        ID: 0,
        icon: "",
        name: "Mean Ground Level",
        valueStr: "0",
        value: 0,
        type: "",
        unit: "Ft",
        quality: 0,
        html: "",
        userTag: 0,
      },
      {
        __Type: "DataValue",
        ID: 1,
        icon: "",
        name: "ALTITUDE LINE",
        valueStr: "10000",
        value: 10000,
        type: "",
        unit: "Ft",
        quality: 0,
        html: "",
        userTag: 0,
      },
      {
        __Type: "DataValue",
        ID: 2,
        icon: "",
        name: "ALTITUDE LINE",
        valueStr: "20000",
        value: 20000,
        type: "",
        unit: "Ft",
        quality: 0,
        html: "",
        userTag: 0,
      },
      {
        __Type: "DataValue",
        ID: 3,
        icon: "",
        name: "ALTITUDE LINE",
        valueStr: "30000",
        value: 30000,
        type: "",
        unit: "Ft",
        quality: 0,
        html: "",
        userTag: 0,
      },
      {
        __Type: "DataValue",
        ID: 4,
        icon: "",
        name: "ALTITUDE LINE",
        valueStr: "40000",
        value: 40000,
        type: "",
        unit: "Ft",
        quality: 0,
        html: "",
        userTag: 0,
      },
      {
        __Type: "DataValue",
        ID: 5,
        icon: "",
        name: "ALTITUDE LINE",
        valueStr: "50000",
        value: 50000,
        type: "",
        unit: "Ft",
        quality: 0,
        html: "",
        userTag: 0,
      },
    ],
    dvMinCloudHeight: {
      __Type: "DataValue",
      ID: 0,
      icon: "",
      name: "MIN_CLOUD_HEIGHT",
      valueStr: "",
      value: 0,
      type: "",
      unit: "Ft",
      quality: 0,
      html: "",
      userTag: 0,
    },
    dvMaxWindSpeed: {
      __Type: "DataValue",
      ID: 0,
      icon: "",
      name: "MAXIMAL_WIND_SPEED",
      valueStr: "",
      value: 77.16999498155383,
      type: "",
      unit: "Km/h",
      quality: 0,
      html: "",
      userTag: 0,
    },
    fMaxGustSpeedRatio: 2,
    fMinGustSpeedRatio: 0.5,
  },
};
